### PR TITLE
Fixes v3 demo

### PR DESCRIPTION
**Pull request by AyushBherwani1998**

### CODE REVIEW

**Comment by matthiasgeihs** [comment]
I've added a commit ("fixup makeEthereumSigner") that resolves #148.
The other 3 commits are just style / cleanup fixes. (Could be removed if not appropriate for this PR.)

**Comment by matthiasgeihs** [comment]
We still need to merge and release the [tkey fixes](https://github.com/tkey/tkey/pull/279) and then update tkey here.

**Comment by matthiasgeihs** [comment]
Resolves #149

**Review by himanshuchawla009 — APPROVED** [review]
lgtm

**Pull request merged**
